version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: havfs_prometheus
    volumes:
      # 挂载你刚才写的配置文件
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    # Linux环境下，为了让容器能访问宿主机的 Python 服务(8000端口)
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: havfs_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus